# Generated by Django 4.2.7 on 2026-01-18 16:11
# Modified to handle missing indexes gracefully

from django.db import migrations


def rename_index_if_exists(apps, schema_editor):
    """Rename index only if it exists"""
    db_alias = schema_editor.connection.alias
    
    # List of index renames: (table_name, old_name, new_name)
    index_renames = [
        ('accounts_account', 'accounts_owner__idx', 'accounts_owner_i_384e13_idx'),
        ('accounts_account', 'accounts_type_c_idx', 'accounts_type_6090fb_idx'),
        ('accounts_accountmember', 'account_me_account_idx', 'account_mem_account_56b540_idx'),
        ('accounts_accountmember', 'account_me_user_id_idx', 'account_mem_user_id_f85498_idx'),
        ('accounts_accountmember', 'account_me_status__idx', 'account_mem_status_9c75e3_idx'),
    ]
    
    with schema_editor.connection.cursor() as cursor:
        for table_name, old_name, new_name in index_renames:
            # Check if index exists
            cursor.execute("""
                SELECT indexname FROM pg_indexes 
                WHERE tablename = %s AND indexname = %s
            """, [table_name, old_name])
            
            if cursor.fetchone():
                # Index exists, rename it
                cursor.execute(f'ALTER INDEX "{old_name}" RENAME TO "{new_name}"')
            # If index doesn't exist, skip (it may already have the new name or never existed)


def reverse_rename_index_if_exists(apps, schema_editor):
    """Reverse rename index only if it exists"""
    db_alias = schema_editor.connection.alias
    
    # Reverse list of index renames
    index_renames = [
        ('accounts_account', 'accounts_owner_i_384e13_idx', 'accounts_owner__idx'),
        ('accounts_account', 'accounts_type_6090fb_idx', 'accounts_type_c_idx'),
        ('accounts_accountmember', 'account_mem_account_56b540_idx', 'account_me_account_idx'),
        ('accounts_accountmember', 'account_mem_user_id_f85498_idx', 'account_me_user_id_idx'),
        ('accounts_accountmember', 'account_mem_status_9c75e3_idx', 'account_me_status__idx'),
    ]
    
    with schema_editor.connection.cursor() as cursor:
        for table_name, new_name, old_name in index_renames:
            cursor.execute("""
                SELECT indexname FROM pg_indexes 
                WHERE tablename = %s AND indexname = %s
            """, [table_name, new_name])
            
            if cursor.fetchone():
                cursor.execute(f'ALTER INDEX "{new_name}" RENAME TO "{old_name}"')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(rename_index_if_exists, reverse_rename_index_if_exists),
    ]
