# Generated by Django 4.2.7 on 2026-01-02 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('remark', models.TextField(blank=True)),
                ('mode', models.CharField(choices=[('Cash', 'Cash'), ('Online', 'Online'), ('Other', 'Other')], default='Cash', max_length=10)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-time'],
                'indexes': [models.Index(fields=['user', '-date', '-time'], name='transaction_user_id_f24fbd_idx'), models.Index(fields=['user', 'type'], name='transaction_user_id_4685bf_idx')],
            },
        ),
    ]
