# Generated by Django 6.0 on 2026-01-11 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_usercustomfield_transaction_attachments_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date', '-time'], 'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.AlterModelOptions(
            name='usercustomfield',
            options={'ordering': ['order', 'field_label'], 'verbose_name': 'User Custom Field', 'verbose_name_plural': 'User Custom Fields'},
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='transaction_user_id_24d890_idx',
            old_name='transaction_user_id_f24fbd_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='transaction_user_id_7b4347_idx',
            old_name='transaction_user_id_4685bf_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='transaction_user_id_cfabf3_idx',
            old_name='transaction_user_id_a385c1_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='transaction_user_id_8841f6_idx',
            old_name='transaction_user_id_4df9e3_idx',
        ),
        migrations.RenameIndex(
            model_name='usercustomfield',
            new_name='user_custom_user_id_8c9dbf_idx',
            old_name='transaction_user_id_1c6951_idx',
        ),
        migrations.AlterModelTable(
            name='transaction',
            table='transactions',
        ),
        migrations.AlterModelTable(
            name='usercustomfield',
            table='user_custom_fields',
        ),
    ]
