# Generated by Django 4.2.7 on 2026-01-18 16:11
# Modified to handle missing indexes gracefully

from django.db import migrations, models
import django.db.models.deletion


def rename_indexes_if_exist(apps, schema_editor):
    """Rename indexes only if they exist"""
    db_alias = schema_editor.connection.alias
    
    index_renames = [
        ('transaction_account_date_time_idx', 'txn_acct_date_time_idx'),
        ('transaction_account_type_idx', 'txn_acct_type_idx'),
    ]
    
    with schema_editor.connection.cursor() as cursor:
        for old_name, new_name in index_renames:
            # Check if old index exists
            cursor.execute("""
                SELECT indexname FROM pg_indexes 
                WHERE tablename = 'transactions' AND indexname = %s
            """, [old_name])
            
            if cursor.fetchone():
                # Check if new index already exists
                cursor.execute("""
                    SELECT indexname FROM pg_indexes 
                    WHERE tablename = 'transactions' AND indexname = %s
                """, [new_name])
                
                if not cursor.fetchone():
                    # Rename the index
                    cursor.execute(f'ALTER INDEX "{old_name}" RENAME TO "{new_name}"')
            else:
                # Old index doesn't exist, check if new one exists (may have been created manually)
                cursor.execute("""
                    SELECT indexname FROM pg_indexes 
                    WHERE tablename = 'transactions' AND indexname = %s
                """, [new_name])
                
                if not cursor.fetchone():
                    # Neither exists, create the new one
                    if old_name == 'transaction_account_date_time_idx':
                        cursor.execute("""
                            CREATE INDEX txn_acct_date_time_idx 
                            ON transactions (account_id, date DESC, time DESC)
                            WHERE account_id IS NOT NULL
                        """)
                    elif old_name == 'transaction_account_type_idx':
                        cursor.execute("""
                            CREATE INDEX txn_acct_type_idx 
                            ON transactions (account_id, type)
                            WHERE account_id IS NOT NULL
                        """)


def alter_account_field_if_needed(apps, schema_editor):
    """Update account field limit_choices_to if needed"""
    db_alias = schema_editor.connection.alias
    
    # Check if account_id column exists
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            SELECT column_name FROM information_schema.columns 
            WHERE table_name='transactions' AND column_name='account_id'
        """)
        
        if cursor.fetchone():
            # Column exists, check if we need to update the constraint
            # The limit_choices_to is a Django-level constraint, not a DB constraint
            # So we don't need to do anything at the database level
            pass


def add_composite_index_if_not_exists(apps, schema_editor):
    """Add composite index if it doesn't exist"""
    db_alias = schema_editor.connection.alias
    
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            SELECT indexname FROM pg_indexes 
            WHERE tablename = 'transactions' AND indexname = 'txn_acct_user_date_idx'
        """)
        
        if not cursor.fetchone():
            cursor.execute("""
                CREATE INDEX txn_acct_user_date_idx 
                ON transactions (account_id, user_id, date DESC, time DESC)
                WHERE account_id IS NOT NULL
            """)


def reverse_rename_indexes(apps, schema_editor):
    """Reverse rename indexes"""
    db_alias = schema_editor.connection.alias
    
    index_renames = [
        ('txn_acct_date_time_idx', 'transaction_account_date_time_idx'),
        ('txn_acct_type_idx', 'transaction_account_type_idx'),
    ]
    
    with schema_editor.connection.cursor() as cursor:
        for new_name, old_name in index_renames:
            cursor.execute("""
                SELECT indexname FROM pg_indexes 
                WHERE tablename = 'transactions' AND indexname = %s
            """, [new_name])
            
            if cursor.fetchone():
                cursor.execute(f'ALTER INDEX "{new_name}" RENAME TO "{old_name}"')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_accounts_owner__idx_accounts_owner_i_384e13_idx_and_more'),
        ('transactions', '0004_merge_0002_add_account_field_0003_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.RunPython(rename_indexes_if_exist, reverse_rename_indexes),
        migrations.RunPython(alter_account_field_if_needed, migrations.RunPython.noop),
        migrations.RunPython(add_composite_index_if_not_exists, migrations.RunPython.noop),
    ]
