# Generated by Django 4.2.7 on 2026-01-18 16:15
# Modified to handle existing account field and indexes gracefully

from django.db import migrations, models
import django.db.models.deletion


def add_account_field_if_not_exists(apps, schema_editor):
    """Add account field only if it doesn't exist"""
    db_alias = schema_editor.connection.alias
    
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            SELECT column_name FROM information_schema.columns 
            WHERE table_name='transactions' AND column_name='account_id'
        """)
        
        if not cursor.fetchone():
            # Field doesn't exist, add it
            Transaction = apps.get_model('transactions', 'Transaction')
            Account = apps.get_model('accounts', 'Account')
            
            field = models.ForeignKey(
                Account,
                on_delete=models.CASCADE,
                related_name='transactions',
                null=True,
                blank=True,
                db_index=True
            )
            field.set_attributes_from_name('account')
            schema_editor.add_field(Transaction, field)


def add_indexes_if_not_exist(apps, schema_editor):
    """Add indexes only if they don't exist"""
    db_alias = schema_editor.connection.alias
    
    indexes_to_add = [
        ('txn_acct_date_time_idx', ['account_id', 'date DESC', 'time DESC']),
        ('txn_acct_type_idx', ['account_id', 'type']),
        ('txn_acct_user_date_idx', ['account_id', 'user_id', 'date DESC', 'time DESC']),
    ]
    
    with schema_editor.connection.cursor() as cursor:
        for index_name, fields in indexes_to_add:
            cursor.execute("""
                SELECT indexname FROM pg_indexes 
                WHERE tablename = 'transactions' AND indexname = %s
            """, [index_name])
            
            if not cursor.fetchone():
                # Index doesn't exist, create it
                fields_str = ', '.join(fields)
                cursor.execute(f"""
                    CREATE INDEX {index_name} 
                    ON transactions ({fields_str})
                    WHERE account_id IS NOT NULL
                """)


def reverse_add_account_field(apps, schema_editor):
    """Remove account field if it exists"""
    db_alias = schema_editor.connection.alias
    
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            SELECT column_name FROM information_schema.columns 
            WHERE table_name='transactions' AND column_name='account_id'
        """)
        
        if cursor.fetchone():
            Transaction = apps.get_model('transactions', 'Transaction')
            field = Transaction._meta.get_field('account')
            schema_editor.remove_field(Transaction, field)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_accounts_owner__idx_accounts_owner_i_384e13_idx_and_more'),
        ('transactions', '0005_rename_transaction_account_date_time_idx_txn_acct_date_time_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(add_account_field_if_not_exists, reverse_add_account_field),
        migrations.RunPython(add_indexes_if_not_exist, migrations.RunPython.noop),
    ]
