# Generated by Django 4.2.7 on 2026-01-18 16:15
# Modified to handle missing indexes gracefully

from django.db import migrations


def rename_indexes_if_exist(apps, schema_editor):
    """Rename indexes only if they exist"""
    db_alias = schema_editor.connection.alias
    
    index_renames = [
        ('notificatio_user_id_idx', 'notificatio_user_id_611c58_idx'),
        ('notificatio_user_id_read_idx', 'notificatio_user_id_cba35e_idx'),
        ('notificatio_account_idx', 'notificatio_account_581948_idx'),
        ('notificatio_type_cre_idx', 'notificatio_type_d2e2f1_idx'),
    ]
    
    with schema_editor.connection.cursor() as cursor:
        for old_name, new_name in index_renames:
            # Check if old index exists
            cursor.execute("""
                SELECT indexname FROM pg_indexes 
                WHERE tablename = 'notifications_notification' AND indexname = %s
            """, [old_name])
            
            if cursor.fetchone():
                # Check if new index already exists
                cursor.execute("""
                    SELECT indexname FROM pg_indexes 
                    WHERE tablename = 'notifications_notification' AND indexname = %s
                """, [new_name])
                
                if not cursor.fetchone():
                    # Rename the index
                    cursor.execute(f'ALTER INDEX "{old_name}" RENAME TO "{new_name}"')
            # If old index doesn't exist, skip (may have been renamed manually or never existed)


def reverse_rename_indexes(apps, schema_editor):
    """Reverse rename indexes"""
    db_alias = schema_editor.connection.alias
    
    index_renames = [
        ('notificatio_user_id_611c58_idx', 'notificatio_user_id_idx'),
        ('notificatio_user_id_cba35e_idx', 'notificatio_user_id_read_idx'),
        ('notificatio_account_581948_idx', 'notificatio_account_idx'),
        ('notificatio_type_d2e2f1_idx', 'notificatio_type_cre_idx'),
    ]
    
    with schema_editor.connection.cursor() as cursor:
        for new_name, old_name in index_renames:
            cursor.execute("""
                SELECT indexname FROM pg_indexes 
                WHERE tablename = 'notifications_notification' AND indexname = %s
            """, [new_name])
            
            if cursor.fetchone():
                cursor.execute(f'ALTER INDEX "{new_name}" RENAME TO "{old_name}"')


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(rename_indexes_if_exist, reverse_rename_indexes),
    ]
